CREATE USER IF NOT EXITS 'wca'@'localhost' 
IDENTIFIED BY 'wca-hub123';
GRANT CREATE, ALTER, DROP, SELECT, INSERT, DELETE, REFERENCES, UPDATE, REPLICATION CLIENT, REPLICATION SLAVE 
ON *.* TO 'wca'@'localhost';
FLUSH PRIVILEGES;

CREATE DATABASE 
IF NOT EXITS wca_hub;



USE wca_hub;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, fname VARCHAR(50), lname VARCHAR(50),
       gender VARCHAR(5), username VARCHAR(50), emailaddress VARCHAR(100), pwd VARCHAR(256));
